### ISSUE TITLE
Invalid HTTPS certificate for peercoin.net as of Sep 14 2016

### ISSUE THREAD

**Issue by hoschiCZ** [super3/peercoin.net#268] opened 2016-09-14 14:55 UTC
On Firefox stable on Windows. FF says it is not trusted because issuer: 
`CN = COMODO RSA Domain Validation Secure Server CA
O = COMODO CA Limited
L = Salford
ST = Greater Manchester
C = GB
` is unknown.

**Comment by hoschiCZ** [comment] 2016-09-14 14:58
Works on Microsoft Edge btw.

**Comment by MAL315** [comment] 2016-09-16 01:32
I'm running Firefox ESR 45.3.0 on Debian and it works fine on mine (says Secure Connection with green padlock).

**Comment by MAL315** [comment] 2016-10-02 18:57
Is it still an issue on your version of Firefox?

**Comment by hoschiCZ** [comment] 2016-10-02 19:08
Yes, it is. FF version 49 on Windows 10.

**Comment by MAL315** [comment] 2016-10-06 02:26
@super3 Might need your help for this one.
https://support.comodo.com/?/Knowledgebase/Article/View/683
https://support.mozilla.org/en-US/questions/1042797

**Comment by D9ping** [comment] 2016-11-01 22:12
The current peercoin.net certificate issued by comodo is expired. (as of 1 november 2016)

**Comment by MAL315** [comment] 2016-11-02 00:01
Yea, super3 bought a new one but just has to put it in. Hopefully it'll fix the firefox issue at the same time.

**Comment by TheWildHorse** [comment] 2016-11-02 13:10
New certificate has been installed and the certificate authority issue fixed.

**Comment by MAL315** [comment] 2016-11-06 03:38
I think we can close this. If the issue isn't resolved on Firefox please open up a new issue and we can investigate. A new certificate was purchased recently so I see no reason for it not to work.

**Closed by MAL315** 2016-11-06 03:38 UTC
